version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: mongodev
        target: /data/db
  notes-microservice:
    image: remax21/notes-microservice
    env_file: ./.env.dev
    ports:
      - 8082:8082
    depends_on:
      - mongodb

volumes:
  mongodev:
